sudo: required
services:
  - docker

before_install:
  - docker build -t dev-client-image -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true dev-client-image npm test

after_success:
  - docker build -t lioneltay/multi-client:latest ./client
  - docker build -t lioneltay/multi-nginx:latest ./nginx
  - docker build -t lioneltay/multi-api:latest ./api
  - docker build -t lioneltay/multi-worker:latest ./worker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push lioneltay/multi-client:latest
  - docker push lioneltay/multi-nginx:latest
  - docker push lioneltay/multi-api:latest
  - docker push lioneltay/multi-worker:latest
