sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in ./keys/travis-deployer-service-account.json.enc -out ./keys/travis-deployer-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file ./keys/travis-deployer-service-account.json
  - gcloud config set project udemy-kubernetes-tekk
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
