sudo: required
services:
  - docker

before_install:
  - docker build -t dev-client-image -f ./client/dev.Dockerfile .

script:
  - docker run -e CI=true dev-client-image npm test

after_success:
  - docker build -t lioneltay/multi-client ./client
  - docker build -t lioneltay/multi-nginx ./nxing
  - docker build -t lioneltay/multi-api ./api
  - docker build -t lioneltay/multi-worker ./worker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push lioneltay/multi-client
  - docker push lioneltay/multi-nginx
  - docker push lioneltay/multi-api
  - docker push lioneltay/multi-worker
