version: "3"
services:
  postgres:
    image: postgres
  redis:
    image: redis
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - 3050:80
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
      - PGPORT=5432
      - PGHOST=postgres
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: dev.Dockerfile
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
